<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>netcoreapp3.1</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>8.0</LangVersion>
		<AvaloniaUseCompiledBindings>true</AvaloniaUseCompiledBindings>
	</PropertyGroup>
	<NoWarn>NU1605</NoWarn>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="0.10.18" />
		<PackageReference Include="Avalonia.Desktop" Version="0.10.18" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="0.10.18" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="0.10.18" />
		<PackageReference Include="Avalonia.Controls.DataGrid" Version="0.10.18" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
		<PackageReference Include="Npgsql" Version="6.0.9" />
		
	</ItemGroup>
</Project>